const express=require("express");
const controller=require("../controllers/clientes-auth.controller");
const { authClienteMiddleware }=require("../middlewares/auth-cliente.middleware");
const router=express.Router();
router.post("/cadastro",controller.cadastro);
router.post("/login",controller.login);
router.post("/esqueci-senha",controller.esqueciSenha);
router.post("/redefinir-senha",controller.redefinirSenha);
router.get("/me",authClienteMiddleware,controller.me);
router.put("/me",authClienteMiddleware,controller.atualizarMe);
router.get("/me/pedidos",authClienteMiddleware,controller.meusPedidos);
router.get("/me/compras-salvas",authClienteMiddleware,controller.comprasSalvas);
router.put("/me/compras-salvas",authClienteMiddleware,controller.salvarCompras);
router.post("/me/pedidos/:venda_id/link-pagamento",authClienteMiddleware,controller.gerarLinkPagamento);
module.exports=router;
