const express=require("express");
const controller=require("../controllers/mercado-pago.controller");
const permissoes=require("../middlewares/permissoes.middleware");
const pin=require("../middlewares/fiscal-pin.middleware");
const auth=require("../middlewares/auth.middleware");
const router=express.Router();
router.post("/webhook",controller.receberWebhook);
router.post("/vendas/:venda_id/criar-preferencia",auth,permissoes(["vendas.criar","relatorios.ver"]),controller.criarPreferencia);
router.post("/vendas/:venda_id/sincronizar-pagamento",auth,permissoes(["vendas.criar","relatorios.ver"]),controller.sincronizarPagamento);
router.get("/vendas/:venda_id",auth,permissoes(["vendas.criar","relatorios.ver"]),controller.buscarPagamentoVenda);
router.get("/webhooks/logs",auth,permissoes(["vendas.criar","relatorios.ver","mercado_pago.configurar"]),controller.listarLogs);
router.get("/config",auth,permissoes(["configuracoes.editar","mercado_pago.configurar"]),controller.obterConfig);
router.put("/config",auth,permissoes(["configuracoes.editar","mercado_pago.configurar"]),pin,controller.salvarConfig);
module.exports=router;
